[package]
name = "processor-cli"
version = "0.1.0"
edition = "2021"


[dependencies]
processor = { path = "../../libs/processor" }


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
