/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

int32_t rust_add(int32_t a, int32_t b);

/**
 * Returns a newly-allocated C string with the ZIP tree or an error message starting with "ERROR:".
 * Caller must free with rust_string_free.
 */
char *rust_zip_list_fd(int32_t fd);

/**
 * Same as rust_zip_list_fd but opens file by path.
 */
char *rust_zip_list_path(const char *path);

/** Frees a string returned by the Rust layer. */
void rust_string_free(char *ptr);
